const form = {
    a1: 'Lubię przyswajać informacje od kogoś lub z książek.',
    a2: 'Lubię wiedzieć, czego wymaga ode mnie nauczyciel.',
    a3: 'Wolę poznawać gotowe rozwiązania zadań niż dochodzić do nich samodzielnie.',
    a4: 'Uczę się raczej systematycznie',
    a5: 'Najchętniej uczę się z zeszytu, w którym mam dobre notatki.',
    a6: 'Kiedy nie umiem rozwiązać zadania, szukam kogoś, kto mi wytłumaczy.',
    a7: 'Uważam, że nauczyciel powinien dyktować mi to, co jest najważniejsze do zapamiętania. ',
    a8: 'Sprawia mi trudność symbolika matematyczna i stosowanie jej w zadaniach obiegających od schematu.',
    b1: 'Lubię uczyć się tego, co przydaje mi się w codziennym życiu.',
    b2: 'Wolę lekcje, na których można wykonać coś praktycznego.',
    b3: 'Niechętnie odrabiam prace domowe. Wolę w tym czasie ugotować, naprawić itp. ',
    b4: 'Moje ulubione przedmioty to WF, plastyka lub technika',
    b5: 'Nie lubię uczyć się teorii.',
    b6: 'Dochodzę do wiedzy poprzez obserwacje, eksperymenty i doświadczenia.',
    b7: 'Wolę własne próby i błędy niż gotową wiedzę przekazaną mi przez dorosłych.',
    b8: 'Lubię rozwiązywać zadania dotyczące codziennych doświadczeń (zakupy,mierzenie itp.)',
    g1: 'Lubię samodzielnie odkrywać nową wiedzę.',
    g2: 'Nie bardzo interesują mnie łatwe tematy przerabiane na lekcjach.',
    g3: 'Wolę uczyć się samodzielnie, korzystając z rozmaitych źródeł.',
    g4: 'Potrafię wiele powiedzieć na prawie każdy temat.',
    g5: 'Ważne dla mnie jest pogłębianie wiedzy (szkolna wiedza jest za płytka).',
    g6: 'Lubię rozwiązywać nowe problemy teoretyczne. Stawiać i analizować pytania.',
    g7: 'Stosuję nietypowe metody rozwiązań zadań, często inne niż podaje nauczyciel.',
    g8: 'Nie przywiązuję dużej wagi do ocen szkolnych. Sama wiedza jest dla mnie ważna.',
    d1: 'Lubię uczyć się rzeczy, które mnie ekscytują, w które mogę się zaangażować. ',
    d2: 'Angażuję się w różne akcje w szkole i/lub poza szkołą.',
    d3: 'Lubię pracować w grupach. Chętnie przewodzę grupom lub pełnię w nich inne role.',
    d4: 'Lubię dyskutować na różne tematy; chętnie zabieram głos na lekcji.',
    d5: 'Interesują mnie zagadnienia o szerszym znaczeniu (polityka, ekologia itp.).',
    d6: 'Mobilizuję się do nauki, kiedy mogę osiągnąć jeszcze inne cele niż wiedza',
    d7: 'Duże znaczenie mają dla mnie dobre relacje z innymi i atmosfera na lekcji. ',
    d8: 'Chciałabym, żeby w zadaniach matematycznych było więcej metafor i emocji (gry konkursy itp.)'
};

export default form;